/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArRouteImport } from './routes/ar'
import { Route as MarrakechRouteImport } from './routes/marrakech'
import { Route as ProRouteImport } from './routes/pro'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiResendDomainRouteImport } from './routes/api/resend-domain'
import { Route as ArMarrakechRouteImport } from './routes/ar_.marrakech'
import { Route as ArProRouteImport } from './routes/ar_.pro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const MarrakechRoute = MarrakechRouteImport.update({
  id: '/marrakech',
  path: '/marrakech',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResendDomainRoute = ApiResendDomainRouteImport.update({
  id: '/api/resend-domain',
  path: '/api/resend-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ArMarrakechRoute = ArMarrakechRouteImport.update({
  id: '/ar_/marrakech',
  path: '/ar/marrakech',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProRoute = ArProRouteImport.update({
  id: '/ar_/pro',
  path: '/ar/pro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/marrakech': typeof MarrakechRoute
  '/pro': typeof ProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/resend-domain': typeof ApiResendDomainRoute
  '/ar/marrakech': typeof ArMarrakechRoute
  '/ar/pro': typeof ArProRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/marrakech': typeof MarrakechRoute
  '/pro': typeof ProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/resend-domain': typeof ApiResendDomainRoute
  '/ar/marrakech': typeof ArMarrakechRoute
  '/ar/pro': typeof ArProRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/marrakech': typeof MarrakechRoute
  '/pro': typeof ProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/resend-domain': typeof ApiResendDomainRoute
  '/ar_/marrakech': typeof ArMarrakechRoute
  '/ar_/pro': typeof ArProRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ar'
    | '/marrakech'
    | '/pro'
    | '/sitemap.xml'
    | '/api/resend-domain'
    | '/ar/marrakech'
    | '/ar/pro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ar'
    | '/marrakech'
    | '/pro'
    | '/sitemap.xml'
    | '/api/resend-domain'
    | '/ar/marrakech'
    | '/ar/pro'
  id:
    | '__root__'
    | '/'
    | '/ar'
    | '/marrakech'
    | '/pro'
    | '/sitemap.xml'
    | '/api/resend-domain'
    | '/ar_/marrakech'
    | '/ar_/pro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArRoute: typeof ArRoute
  MarrakechRoute: typeof MarrakechRoute
  ProRoute: typeof ProRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiResendDomainRoute: typeof ApiResendDomainRoute
  ArMarrakechRoute: typeof ArMarrakechRoute
  ArProRoute: typeof ArProRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marrakech': {
      id: '/marrakech'
      path: '/marrakech'
      fullPath: '/marrakech'
      preLoaderRoute: typeof MarrakechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resend-domain': {
      id: '/api/resend-domain'
      path: '/api/resend-domain'
      fullPath: '/api/resend-domain'
      preLoaderRoute: typeof ApiResendDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/marrakech': {
      id: '/ar_/marrakech'
      path: '/ar/marrakech'
      fullPath: '/ar/marrakech'
      preLoaderRoute: typeof ArMarrakechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/pro': {
      id: '/ar_/pro'
      path: '/ar/pro'
      fullPath: '/ar/pro'
      preLoaderRoute: typeof ArProRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArRoute: ArRoute,
  MarrakechRoute: MarrakechRoute,
  ProRoute: ProRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiResendDomainRoute: ApiResendDomainRoute,
  ArMarrakechRoute: ArMarrakechRoute,
  ArProRoute: ArProRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
