/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArRouteImport } from './routes/ar'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MarrakechRouteImport } from './routes/marrakech'
import { Route as ProRouteImport } from './routes/pro'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiResendDomainRouteImport } from './routes/api/resend-domain'
import { Route as ArInscriptionRouteImport } from './routes/ar_.inscription'
import { Route as ArMarrakechRouteImport } from './routes/ar_.marrakech'
import { Route as ArProRouteImport } from './routes/ar_.pro'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ArServicesIndexRouteImport } from './routes/ar_.services.index'
import { Route as ArServicesSlugRouteImport } from './routes/ar_.services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MarrakechRoute = MarrakechRouteImport.update({
  id: '/marrakech',
  path: '/marrakech',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResendDomainRoute = ApiResendDomainRouteImport.update({
  id: '/api/resend-domain',
  path: '/api/resend-domain',
  getParentRoute: () => rootRouteImport,
} as any)
const ArInscriptionRoute = ArInscriptionRouteImport.update({
  id: '/ar_/inscription',
  path: '/ar/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ArMarrakechRoute = ArMarrakechRouteImport.update({
  id: '/ar_/marrakech',
  path: '/ar/marrakech',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProRoute = ArProRouteImport.update({
  id: '/ar_/pro',
  path: '/ar/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArServicesIndexRoute = ArServicesIndexRouteImport.update({
  id: '/ar_/services/',
  path: '/ar/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArServicesSlugRoute = ArServicesSlugRouteImport.update({
  id: '/ar_/services/$slug',
  path: '/ar/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/inscription': typeof InscriptionRoute
  '/marrakech': typeof MarrakechRoute
  '/pro': typeof ProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/resend-domain': typeof ApiResendDomainRoute
  '/ar/inscription': typeof ArInscriptionRoute
  '/ar/marrakech': typeof ArMarrakechRoute
  '/ar/pro': typeof ArProRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/services/': typeof ArServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/inscription': typeof InscriptionRoute
  '/marrakech': typeof MarrakechRoute
  '/pro': typeof ProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/resend-domain': typeof ApiResendDomainRoute
  '/ar/inscription': typeof ArInscriptionRoute
  '/ar/marrakech': typeof ArMarrakechRoute
  '/ar/pro': typeof ArProRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/ar/services/$slug': typeof ArServicesSlugRoute
  '/ar/services': typeof ArServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar': typeof ArRoute
  '/inscription': typeof InscriptionRoute
  '/marrakech': typeof MarrakechRoute
  '/pro': typeof ProRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/resend-domain': typeof ApiResendDomainRoute
  '/ar_/inscription': typeof ArInscriptionRoute
  '/ar_/marrakech': typeof ArMarrakechRoute
  '/ar_/pro': typeof ArProRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/ar_/services/$slug': typeof ArServicesSlugRoute
  '/ar_/services/': typeof ArServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ar'
    | '/inscription'
    | '/marrakech'
    | '/pro'
    | '/sitemap.xml'
    | '/api/resend-domain'
    | '/ar/inscription'
    | '/ar/marrakech'
    | '/ar/pro'
    | '/services/$slug'
    | '/services/'
    | '/ar/services/$slug'
    | '/ar/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ar'
    | '/inscription'
    | '/marrakech'
    | '/pro'
    | '/sitemap.xml'
    | '/api/resend-domain'
    | '/ar/inscription'
    | '/ar/marrakech'
    | '/ar/pro'
    | '/services/$slug'
    | '/services'
    | '/ar/services/$slug'
    | '/ar/services'
  id:
    | '__root__'
    | '/'
    | '/ar'
    | '/inscription'
    | '/marrakech'
    | '/pro'
    | '/sitemap.xml'
    | '/api/resend-domain'
    | '/ar_/inscription'
    | '/ar_/marrakech'
    | '/ar_/pro'
    | '/services/$slug'
    | '/services/'
    | '/ar_/services/$slug'
    | '/ar_/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArRoute: typeof ArRoute
  InscriptionRoute: typeof InscriptionRoute
  MarrakechRoute: typeof MarrakechRoute
  ProRoute: typeof ProRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiResendDomainRoute: typeof ApiResendDomainRoute
  ArInscriptionRoute: typeof ArInscriptionRoute
  ArMarrakechRoute: typeof ArMarrakechRoute
  ArProRoute: typeof ArProRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ArServicesSlugRoute: typeof ArServicesSlugRoute
  ArServicesIndexRoute: typeof ArServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marrakech': {
      id: '/marrakech'
      path: '/marrakech'
      fullPath: '/marrakech'
      preLoaderRoute: typeof MarrakechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resend-domain': {
      id: '/api/resend-domain'
      path: '/api/resend-domain'
      fullPath: '/api/resend-domain'
      preLoaderRoute: typeof ApiResendDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/inscription': {
      id: '/ar_/inscription'
      path: '/ar/inscription'
      fullPath: '/ar/inscription'
      preLoaderRoute: typeof ArInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/marrakech': {
      id: '/ar_/marrakech'
      path: '/ar/marrakech'
      fullPath: '/ar/marrakech'
      preLoaderRoute: typeof ArMarrakechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/pro': {
      id: '/ar_/pro'
      path: '/ar/pro'
      fullPath: '/ar/pro'
      preLoaderRoute: typeof ArProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/services/': {
      id: '/ar_/services/'
      path: '/ar/services'
      fullPath: '/ar/services/'
      preLoaderRoute: typeof ArServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar_/services/$slug': {
      id: '/ar_/services/$slug'
      path: '/ar/services/$slug'
      fullPath: '/ar/services/$slug'
      preLoaderRoute: typeof ArServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArRoute: ArRoute,
  InscriptionRoute: InscriptionRoute,
  MarrakechRoute: MarrakechRoute,
  ProRoute: ProRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiResendDomainRoute: ApiResendDomainRoute,
  ArInscriptionRoute: ArInscriptionRoute,
  ArMarrakechRoute: ArMarrakechRoute,
  ArProRoute: ArProRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ArServicesSlugRoute: ArServicesSlugRoute,
  ArServicesIndexRoute: ArServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
